export const cardsArr = [
  { _id: 1, a: { word: 'have' }, b: { word: 'иметь' } },
  { _id: 2, a: { word: 'you' }, b: { word: 'ты / вы' } },
  { _id: 3, a: { word: 'he' }, b: { word: 'он' } },
  { _id: 4, a: { word: 'they' }, b: { word: 'они' } },
  { _id: 5, a: { word: 'that' }, b: { word: 'что / тот' } },
  { _id: 6, a: { word: 'we' }, b: { word: 'мы' } },
  { _id: 7, a: { word: 'i' }, b: { word: 'я' } },
  { _id: 8, a: { word: 'she' }, b: { word: 'она' } },
  { _id: 9, a: { word: 'but' }, b: { word: 'но' } },
  { _id: 10, a: { word: 'from' }, b: { word: 'из / от' } },
  { _id: 11, a: { word: 'will' }, b: { word: 'будет / воля' } },
  { _id: 12, a: { word: 'or' }, b: { word: 'или' } },
  { _id: 13, a: { word: 'say' }, b: { word: 'сказать' } },
  { _id: 14, a: { word: 'go' }, b: { word: 'идти' } },
  { _id: 15, a: { word: 'so' }, b: { word: 'так / поэтому' } },
  { _id: 16, a: { word: 'all' }, b: { word: 'все' } },
  { _id: 17, a: { word: 'if' }, b: { word: 'если' } },
  { _id: 18, a: { word: 'one' }, b: { word: 'один' } },
  { _id: 19, a: { word: 'would' }, b: { word: 'бы' } },
  { _id: 20, a: { word: 'about' }, b: { word: 'о / около' } },
  { _id: 21, a: { word: 'can' }, b: { word: 'мочь' } },
  { _id: 22, a: { word: 'which' }, b: { word: 'который' } },
  { _id: 23, a: { word: 'there' }, b: { word: 'там' } },
  { _id: 24, a: { word: 'know' }, b: { word: 'знать' } },
  { _id: 25, a: { word: 'more' }, b: { word: 'больше' } },
  { _id: 26, a: { word: 'get' }, b: { word: 'получать' } },
  { _id: 27, a: { word: 'who' }, b: { word: 'кто' } },
  { _id: 28, a: { word: 'like' }, b: { word: 'нравиться / как' } },
  { _id: 29, a: { word: 'when' }, b: { word: 'когда' } },
  { _id: 30, a: { word: 'think' }, b: { word: 'думать' } },
  { _id: 31, a: { word: 'make' }, b: { word: 'делать' } },
  { _id: 32, a: { word: 'time' }, b: { word: 'время' } },
  { _id: 33, a: { word: 'see' }, b: { word: 'видеть' } },
  { _id: 34, a: { word: 'what' }, b: { word: 'что' } },
  { _id: 35, a: { word: 'up' }, b: { word: 'вверх' } },
  { _id: 36, a: { word: 'some' }, b: { word: 'некоторые' } },
  { _id: 37, a: { word: 'other' }, b: { word: 'другой' } },
  { _id: 38, a: { word: 'out' }, b: { word: 'вне / наружу' } },
  { _id: 39, a: { word: 'good' }, b: { word: 'хороший' } },
  { _id: 40, a: { word: 'people' }, b: { word: 'люди' } },
  { _id: 41, a: { word: 'year' }, b: { word: 'год' } },
  { _id: 42, a: { word: 'take' }, b: { word: 'брать' } },
  { _id: 43, a: { word: 'no' }, b: { word: 'нет' } },
  { _id: 44, a: { word: 'well' }, b: { word: 'хорошо' } },
  { _id: 45, a: { word: 'because' }, b: { word: 'потому что' } },
  { _id: 46, a: { word: 'very' }, b: { word: 'очень' } },
  { _id: 47, a: { word: 'just' }, b: { word: 'просто / только' } },
  { _id: 48, a: { word: 'come' }, b: { word: 'приходить' } },
  { _id: 49, a: { word: 'could' }, b: { word: 'мог бы' } },
  { _id: 50, a: { word: 'work' }, b: { word: 'работа / работать' } },
  { _id: 51, a: { word: 'use' }, b: { word: 'использовать' } },
  { _id: 52, a: { word: 'than' }, b: { word: 'чем' } },
  { _id: 53, a: { word: 'now' }, b: { word: 'сейчас' } },
  { _id: 54, a: { word: 'then' }, b: { word: 'тогда' } },
  { _id: 55, a: { word: 'also' }, b: { word: 'также' } },
  { _id: 56, a: { word: 'into' }, b: { word: 'внутрь' } },
  { _id: 57, a: { word: 'only' }, b: { word: 'только' } },
  { _id: 58, a: { word: 'look' }, b: { word: 'смотреть' } },
  { _id: 59, a: { word: 'want' }, b: { word: 'хотеть' } },
  { _id: 60, a: { word: 'give' }, b: { word: 'давать' } },
  { _id: 61, a: { word: 'first' }, b: { word: 'первый' } },
  { _id: 62, a: { word: 'new' }, b: { word: 'новый' } },
  { _id: 63, a: { word: 'way' }, b: { word: 'путь / способ' } },
  { _id: 64, a: { word: 'find' }, b: { word: 'находить' } },
  { _id: 65, a: { word: 'over' }, b: { word: 'над / через' } },
  { _id: 66, a: { word: 'any' }, b: { word: 'любой' } },
  { _id: 67, a: { word: 'after' }, b: { word: 'после' } },
  { _id: 68, a: { word: 'day' }, b: { word: 'день' } },
  { _id: 69, a: { word: 'where' }, b: { word: 'где' } },
  { _id: 70, a: { word: 'thing' }, b: { word: 'вещь' } },
  { _id: 71, a: { word: 'most' }, b: { word: 'большинство' } },
  { _id: 72, a: { word: 'should' }, b: { word: 'должен' } },
  { _id: 73, a: { word: 'need' }, b: { word: 'нуждаться' } },
  { _id: 74, a: { word: 'much' }, b: { word: 'много' } },
  { _id: 75, a: { word: 'right' }, b: { word: 'правильный / право' } },
  { _id: 76, a: { word: 'how' }, b: { word: 'как' } },
  { _id: 77, a: { word: 'back' }, b: { word: 'назад' } },
  { _id: 78, a: { word: 'mean' }, b: { word: 'значить' } },
  { _id: 79, a: { word: 'even' }, b: { word: 'даже' } },
  { _id: 80, a: { word: 'may' }, b: { word: 'мочь / май' } },
  { _id: 81, a: { word: 'here' }, b: { word: 'здесь' } },
  { _id: 82, a: { word: 'many' }, b: { word: 'многие' } },
  { _id: 83, a: { word: 'such' }, b: { word: 'такой' } },
  { _id: 84, a: { word: 'last' }, b: { word: 'последний' } },
  { _id: 85, a: { word: 'child' }, b: { word: 'ребенок' } },
  { _id: 86, a: { word: 'tell' }, b: { word: 'рассказывать' } },
  { _id: 87, a: { word: 'really' }, b: { word: 'действительно' } },
  { _id: 88, a: { word: 'call' }, b: { word: 'звонить' } },
  { _id: 89, a: { word: 'before' }, b: { word: 'до' } },
  { _id: 90, a: { word: 'company' }, b: { word: 'компания' } },
  { _id: 91, a: { word: 'through' }, b: { word: 'через' } },
  { _id: 92, a: { word: 'down' }, b: { word: 'вниз' } },
  { _id: 93, a: { word: 'show' }, b: { word: 'показывать' } },
  { _id: 94, a: { word: 'life' }, b: { word: 'жизнь' } },
  { _id: 95, a: { word: 'man' }, b: { word: 'мужчина' } },
  { _id: 96, a: { word: 'change' }, b: { word: 'изменять' } },
  { _id: 97, a: { word: 'place' }, b: { word: 'место' } },
  { _id: 98, a: { word: 'long' }, b: { word: 'долгий' } },
  { _id: 99, a: { word: 'between' }, b: { word: 'между' } },
  { _id: 100, a: { word: 'feel' }, b: { word: 'чувствовать' } },
  { _id: 101, a: { word: 'too' }, b: { word: 'слишком' } },
  { _id: 102, a: { word: 'still' }, b: { word: 'все еще' } },
  { _id: 103, a: { word: 'problem' }, b: { word: 'проблема' } },
  { _id: 104, a: { word: 'write' }, b: { word: 'писать' } },
  { _id: 105, a: { word: 'same' }, b: { word: 'тот же' } },
  { _id: 106, a: { word: 'lot' }, b: { word: 'много' } },
  { _id: 107, a: { word: 'great' }, b: { word: 'отличный' } },
  { _id: 108, a: { word: 'try' }, b: { word: 'пытаться' } },
  { _id: 109, a: { word: 'leave' }, b: { word: 'оставлять' } },
  { _id: 110, a: { word: 'number' }, b: { word: 'число' } },
  { _id: 111, a: { word: 'both' }, b: { word: 'оба' } },
  { _id: 112, a: { word: 'own' }, b: { word: 'собственный' } },
  { _id: 113, a: { word: 'part' }, b: { word: 'часть' } },
  { _id: 114, a: { word: 'point' }, b: { word: 'точка' } },
  { _id: 115, a: { word: 'little' }, b: { word: 'маленький' } },
  { _id: 116, a: { word: 'help' }, b: { word: 'помогать' } },
  { _id: 117, a: { word: 'ask' }, b: { word: 'спрашивать' } },
  { _id: 118, a: { word: 'meet' }, b: { word: 'встречать' } },
  { _id: 119, a: { word: 'start' }, b: { word: 'начинать' } },
  { _id: 120, a: { word: 'talk' }, b: { word: 'говорить' } },
  { _id: 121, a: { word: 'something' }, b: { word: 'что-то' } },
  { _id: 122, a: { word: 'put' }, b: { word: 'класть' } },
  { _id: 123, a: { word: 'another' }, b: { word: 'другой' } },
  { _id: 124, a: { word: 'become' }, b: { word: 'становиться' } },
  { _id: 125, a: { word: 'interest' }, b: { word: 'интерес' } },
  { _id: 126, a: { word: 'country' }, b: { word: 'страна' } },
  { _id: 127, a: { word: 'old' }, b: { word: 'старый' } },
  { _id: 128, a: { word: 'each' }, b: { word: 'каждый' } },
  { _id: 129, a: { word: 'school' }, b: { word: 'школа' } },
  { _id: 130, a: { word: 'late' }, b: { word: 'поздний' } },
  { _id: 131, a: { word: 'high' }, b: { word: 'высокий' } },
  { _id: 132, a: { word: 'different' }, b: { word: 'разный' } },
  { _id: 133, a: { word: 'off' }, b: { word: 'выключен' } },
  { _id: 134, a: { word: 'next' }, b: { word: 'следующий' } },
  { _id: 135, a: { word: 'end' }, b: { word: 'конец' } },
  { _id: 136, a: { word: 'live' }, b: { word: 'жить' } },
  { _id: 137, a: { word: 'why' }, b: { word: 'почему' } },
  { _id: 138, a: { word: 'while' }, b: { word: 'пока' } },
  { _id: 139, a: { word: 'world' }, b: { word: 'мир' } },
  { _id: 140, a: { word: 'week' }, b: { word: 'неделя' } },
  { _id: 141, a: { word: 'play' }, b: { word: 'играть' } },
  { _id: 142, a: { word: 'might' }, b: { word: 'мочь' } },
  { _id: 143, a: { word: 'must' }, b: { word: 'должен' } },
  { _id: 144, a: { word: 'home' }, b: { word: 'дом' } },
  { _id: 145, a: { word: 'never' }, b: { word: 'никогда' } },
  { _id: 146, a: { word: 'include' }, b: { word: 'включать' } },
  { _id: 147, a: { word: 'course' }, b: { word: 'курс' } },
  { _id: 148, a: { word: 'house' }, b: { word: 'дом' } },
  { _id: 149, a: { word: 'report' }, b: { word: 'отчет' } },
  { _id: 150, a: { word: 'group' }, b: { word: 'группа' } },
  { _id: 151, a: { word: 'case' }, b: { word: 'случай' } },
  { _id: 152, a: { word: 'woman' }, b: { word: 'женщина' } },
  { _id: 153, a: { word: 'around' }, b: { word: 'вокруг' } },
  { _id: 154, a: { word: 'book' }, b: { word: 'книга' } },
  { _id: 155, a: { word: 'family' }, b: { word: 'семья' } },
  { _id: 156, a: { word: 'seem' }, b: { word: 'казаться' } },
  { _id: 157, a: { word: 'let' }, b: { word: 'позволять' } },
  { _id: 158, a: { word: 'again' }, b: { word: 'снова' } },
  { _id: 159, a: { word: 'kind' }, b: { word: 'вид / добрый' } },
  { _id: 160, a: { word: 'keep' }, b: { word: 'держать' } },
  { _id: 161, a: { word: 'hear' }, b: { word: 'слышать' } },
  { _id: 162, a: { word: 'system' }, b: { word: 'система' } },
  { _id: 163, a: { word: 'every' }, b: { word: 'каждый' } },
  { _id: 164, a: { word: 'question' }, b: { word: 'вопрос' } },
  { _id: 165, a: { word: 'during' }, b: { word: 'во время' } },
  { _id: 166, a: { word: 'always' }, b: { word: 'всегда' } },
  { _id: 167, a: { word: 'big' }, b: { word: 'большой' } },
  { _id: 168, a: { word: 'set' }, b: { word: 'набор / устанавливать' } },
  { _id: 169, a: { word: 'small' }, b: { word: 'маленький' } },
  { _id: 170, a: { word: 'study' }, b: { word: 'учиться' } },
  { _id: 171, a: { word: 'follow' }, b: { word: 'следовать' } },
  { _id: 172, a: { word: 'begin' }, b: { word: 'начинать' } },
  { _id: 173, a: { word: 'important' }, b: { word: 'важный' } },
  { _id: 174, a: { word: 'since' }, b: { word: 'с тех пор как' } },
  { _id: 175, a: { word: 'run' }, b: { word: 'бежать' } },
  { _id: 176, a: { word: 'under' }, b: { word: 'под' } },
  { _id: 177, a: { word: 'turn' }, b: { word: 'поворачивать' } },
  { _id: 178, a: { word: 'few' }, b: { word: 'несколько' } },
  { _id: 179, a: { word: 'bring' }, b: { word: 'приносить' } },
  { _id: 180, a: { word: 'early' }, b: { word: 'ранний' } },
  { _id: 181, a: { word: 'hand' }, b: { word: 'рука' } },
  { _id: 182, a: { word: 'state' }, b: { word: 'состояние / штат' } },
  { _id: 183, a: { word: 'move' }, b: { word: 'двигаться' } },
  { _id: 184, a: { word: 'money' }, b: { word: 'деньги' } },
  { _id: 185, a: { word: 'fact' }, b: { word: 'факт' } },
  { _id: 186, a: { word: 'however' }, b: { word: 'однако' } },
  { _id: 187, a: { word: 'area' }, b: { word: 'область / район' } },
  { _id: 188, a: { word: 'provide' }, b: { word: 'предоставлять' } },
  { _id: 189, a: { word: 'name' }, b: { word: 'имя / название' } },
  { _id: 190, a: { word: 'read' }, b: { word: 'читать' } },
  { _id: 191, a: { word: 'friend' }, b: { word: 'друг' } },
  { _id: 192, a: { word: 'month' }, b: { word: 'месяц' } },
  { _id: 193, a: { word: 'large' }, b: { word: 'большой' } },
  { _id: 194, a: { word: 'business' }, b: { word: 'бизнес / дело' } },
  { _id: 195, a: { word: 'without' }, b: { word: 'без' } },
  { _id: 196, a: { word: 'information' }, b: { word: 'информация' } },
  { _id: 197, a: { word: 'open' }, b: { word: 'открывать / открытый' } },
  { _id: 198, a: { word: 'order' }, b: { word: 'заказ / порядок' } },
  { _id: 199, a: { word: 'government' }, b: { word: 'правительство' } },
  { _id: 200, a: { word: 'word' }, b: { word: 'слово' } },
  { _id: 201, a: { word: 'issue' }, b: { word: 'вопрос / проблема' } },
  { _id: 202, a: { word: 'market' }, b: { word: 'рынок' } },
  { _id: 203, a: { word: 'pay' }, b: { word: 'платить' } },
  { _id: 204, a: { word: 'build' }, b: { word: 'строить' } },
  { _id: 205, a: { word: 'hold' }, b: { word: 'держать / проводить' } },
  { _id: 206, a: { word: 'service' }, b: { word: 'услуга / сервис' } },
  { _id: 207, a: { word: 'against' }, b: { word: 'против' } },
  { _id: 208, a: { word: 'believe' }, b: { word: 'верить' } },
  { _id: 209, a: { word: 'second' }, b: { word: 'второй / секунда' } },
  { _id: 210, a: { word: 'though' }, b: { word: 'хотя' } },
  { _id: 211, a: { word: 'yes' }, b: { word: 'да' } },
  { _id: 212, a: { word: 'love' }, b: { word: 'любовь / любить' } },
  { _id: 213, a: { word: 'increase' }, b: { word: 'увеличивать / рост' } },
  { _id: 214, a: { word: 'job' }, b: { word: 'работа' } },
  { _id: 215, a: { word: 'plan' }, b: { word: 'планировать / план' } },
  { _id: 216, a: { word: 'result' }, b: { word: 'результат' } },
  { _id: 217, a: { word: 'away' }, b: { word: 'далеко / прочь' } },
  { _id: 218, a: { word: 'example' }, b: { word: 'пример' } },
  { _id: 219, a: { word: 'happen' }, b: { word: 'происходить' } },
  { _id: 220, a: { word: 'offer' }, b: { word: 'предлагать / предложение' } },
  { _id: 221, a: { word: 'young' }, b: { word: 'молодой' } },
  { _id: 222, a: { word: 'close' }, b: { word: 'закрывать / близкий' } },
  { _id: 223, a: { word: 'program' }, b: { word: 'программа' } },
  { _id: 224, a: { word: 'lead' }, b: { word: 'вести / руководство' } },
  { _id: 225, a: { word: 'buy' }, b: { word: 'покупать' } },
  { _id: 226, a: { word: 'understand' }, b: { word: 'понимать' } },
  { _id: 227, a: { word: 'thank' }, b: { word: 'благодарить' } },
  { _id: 228, a: { word: 'far' }, b: { word: 'далеко' } },
  { _id: 229, a: { word: 'today' }, b: { word: 'сегодня' } },
  { _id: 230, a: { word: 'hour' }, b: { word: 'час' } },
  { _id: 231, a: { word: 'student' }, b: { word: 'студент' } },
  { _id: 232, a: { word: 'face' }, b: { word: 'лицо / сталкиваться' } },
  { _id: 233, a: { word: 'hope' }, b: { word: 'надежда / надеяться' } },
  { _id: 234, a: { word: 'idea' }, b: { word: 'идея' } },
  { _id: 235, a: { word: 'cost' }, b: { word: 'стоить / стоимость' } },
  { _id: 236, a: { word: 'less' }, b: { word: 'меньше' } },
  { _id: 237, a: { word: 'room' }, b: { word: 'комната / место' } },
  { _id: 238, a: { word: 'until' }, b: { word: 'до (времени)' } },
  { _id: 239, a: { word: 'reason' }, b: { word: 'причина' } },
  { _id: 240, a: { word: 'form' }, b: { word: 'форма / образовывать' } },
  { _id: 241, a: { word: 'spend' }, b: { word: 'тратить' } },
  { _id: 242, a: { word: 'head' }, b: { word: 'голова / руководитель' } },
  { _id: 243, a: { word: 'car' }, b: { word: 'машина' } },
  { _id: 244, a: { word: 'learn' }, b: { word: 'учиться' } },
  { _id: 245, a: { word: 'level' }, b: { word: 'уровень' } },
  { _id: 246, a: { word: 'person' }, b: { word: 'человек' } },
  { _id: 247, a: { word: 'experience' }, b: { word: 'опыт' } },
  { _id: 248, a: { word: 'once' }, b: { word: 'однажды / один раз' } },
  { _id: 249, a: { word: 'member' }, b: { word: 'участник / член' } },
  { _id: 250, a: { word: 'enough' }, b: { word: 'достаточно' } },
  { _id: 251, a: { word: 'bad' }, b: { word: 'плохой' } },
  { _id: 252, a: { word: 'city' }, b: { word: 'город' } },
  { _id: 253, a: { word: 'night' }, b: { word: 'ночь' } },
  { _id: 254, a: { word: 'able' }, b: { word: 'способный / мочь' } },
  { _id: 255, a: { word: 'support' }, b: { word: 'поддержка / поддерживать' } },
  { _id: 256, a: { word: 'whether' }, b: { word: 'ли / независимо от того' } },
  { _id: 257, a: { word: 'line' }, b: { word: 'линия / строка' } },
  { _id: 258, a: { word: 'present' }, b: { word: 'настоящее / присутствовать' } },
  { _id: 259, a: { word: 'side' }, b: { word: 'сторона' } },
  { _id: 260, a: { word: 'quite' }, b: { word: 'вполне / довольно' } },
  { _id: 261, a: { word: 'although' }, b: { word: 'хотя' } },
  { _id: 262, a: { word: 'sure' }, b: { word: 'уверенный / точно' } },
  { _id: 263, a: { word: 'term' }, b: { word: 'срок / термин' } },
  { _id: 264, a: { word: 'least' }, b: { word: 'наименьший / по крайней мере' } },
  { _id: 265, a: { word: 'age' }, b: { word: 'возраст' } },
  { _id: 266, a: { word: 'low' }, b: { word: 'низкий' } },
  { _id: 267, a: { word: 'speak' }, b: { word: 'говорить' } },
  { _id: 268, a: { word: 'within' }, b: { word: 'внутри / в пределах' } },
  { _id: 269, a: { word: 'process' }, b: { word: 'процесс' } },
  { _id: 270, a: { word: 'public' }, b: { word: 'публичный / общественный' } },
  { _id: 271, a: { word: 'often' }, b: { word: 'часто' } },
  { _id: 272, a: { word: 'train' }, b: { word: 'поезд / тренировать' } },
  { _id: 273, a: { word: 'possible' }, b: { word: 'возможный' } },
  { _id: 274, a: { word: 'actually' }, b: { word: 'на самом деле' } },
  { _id: 275, a: { word: 'rather' }, b: { word: 'скорее / довольно' } },
  { _id: 276, a: { word: 'view' }, b: { word: 'взгляд / вид' } },
  { _id: 277, a: { word: 'together' }, b: { word: 'вместе' } },
  { _id: 278, a: { word: 'consider' }, b: { word: 'рассматривать / считать' } },
  { _id: 279, a: { word: 'price' }, b: { word: 'цена' } },
  { _id: 280, a: { word: 'parent' }, b: { word: 'родитель' } },
  { _id: 281, a: { word: 'hard' }, b: { word: 'трудный / твёрдый' } },
  { _id: 282, a: { word: 'party' }, b: { word: 'партия / вечеринка' } },
  { _id: 283, a: { word: 'local' }, b: { word: 'местный' } },
  { _id: 284, a: { word: 'control' }, b: { word: 'контроль / управлять' } },
  { _id: 285, a: { word: 'already' }, b: { word: 'уже' } },
  { _id: 286, a: { word: 'concern' }, b: { word: 'беспокойство / касаться' } },
  { _id: 287, a: { word: 'product' }, b: { word: 'продукт' } },
  { _id: 288, a: { word: 'lose' }, b: { word: 'терять / проигрывать' } },
  { _id: 289, a: { word: 'story' }, b: { word: 'история / рассказ' } },
  { _id: 290, a: { word: 'almost' }, b: { word: 'почти' } },
  { _id: 291, a: { word: 'continue' }, b: { word: 'продолжать' } },
  { _id: 292, a: { word: 'stand' }, b: { word: 'стоять / позиция' } },
  { _id: 293, a: { word: 'whole' }, b: { word: 'целый' } },
  { _id: 294, a: { word: 'yet' }, b: { word: 'ещё / уже (в отриц.)' } },
  { _id: 295, a: { word: 'rate' }, b: { word: 'ставка / оценивать' } },
  { _id: 296, a: { word: 'care' }, b: { word: 'забота / заботиться' } },
  { _id: 297, a: { word: 'expect' }, b: { word: 'ожидать' } },
  { _id: 298, a: { word: 'effect' }, b: { word: 'эффект / влияние' } },
  { _id: 299, a: { word: 'sort' }, b: { word: 'тип / сортировать' } },
  { _id: 300, a: { word: 'ever' }, b: { word: 'когда-либо' } },
  { _id: 301, a: { word: 'anything' }, b: { word: 'что угодно' } },
  { _id: 302, a: { word: 'cause' }, b: { word: 'причина / вызывать' } },
  { _id: 303, a: { word: 'fall' }, b: { word: 'падать / осень' } },
  { _id: 304, a: { word: 'deal' }, b: { word: 'сделка / иметь дело' } },
  { _id: 305, a: { word: 'water' }, b: { word: 'вода' } },
  { _id: 306, a: { word: 'send' }, b: { word: 'отправлять' } },
  { _id: 307, a: { word: 'allow' }, b: { word: 'разрешать' } },
  { _id: 308, a: { word: 'soon' }, b: { word: 'скоро' } },
  { _id: 309, a: { word: 'watch' }, b: { word: 'смотреть / часы' } },
  { _id: 310, a: { word: 'base' }, b: { word: 'основа / базировать' } },
  { _id: 311, a: { word: 'probably' }, b: { word: 'вероятно' } },
  { _id: 312, a: { word: 'suggest' }, b: { word: 'предлагать / предполагать' } },
  { _id: 313, a: { word: 'past' }, b: { word: 'прошлое / прошлый' } },
  { _id: 314, a: { word: 'power' }, b: { word: 'сила / власть' } },
  { _id: 315, a: { word: 'test' }, b: { word: 'тест / проверять' } },
  { _id: 316, a: { word: 'visit' }, b: { word: 'посещать / визит' } },
  { _id: 317, a: { word: 'center' }, b: { word: 'центр' } },
  { _id: 318, a: { word: 'grow' }, b: { word: 'расти' } },
  { _id: 319, a: { word: 'nothing' }, b: { word: 'ничего' } },
  { _id: 320, a: { word: 'return' }, b: { word: 'возвращаться / возврат' } },
  { _id: 321, a: { word: 'mother' }, b: { word: 'мать' } },
  { _id: 322, a: { word: 'walk' }, b: { word: 'идти / прогулка' } },
  { _id: 323, a: { word: 'matter' }, b: { word: 'иметь значение / материя' } },
  { _id: 324, a: { word: 'mind' }, b: { word: 'разум / возражать' } },
  { _id: 325, a: { word: 'value' }, b: { word: 'ценность / ценить' } },
  { _id: 326, a: { word: 'office' }, b: { word: 'офис' } },
  { _id: 327, a: { word: 'record' }, b: { word: 'запись / рекорд' } },
  { _id: 328, a: { word: 'stay' }, b: { word: 'оставаться / жить' } },
  { _id: 329, a: { word: 'force' }, b: { word: 'сила / заставлять' } },
  { _id: 330, a: { word: 'stop' }, b: { word: 'останавливать / остановка' } },
  { _id: 331, a: { word: 'several' }, b: { word: 'несколько' } },
  { _id: 332, a: { word: 'light' }, b: { word: 'свет / лёгкий' } },
  { _id: 333, a: { word: 'develop' }, b: { word: 'развивать' } },
  { _id: 334, a: { word: 'remember' }, b: { word: 'помнить' } },
  { _id: 335, a: { word: 'bit' }, b: { word: 'немного / кусочек' } },
  { _id: 336, a: { word: 'share' }, b: { word: 'делиться / доля' } },
  { _id: 337, a: { word: 'real' }, b: { word: 'реальный / настоящий' } },
  { _id: 338, a: { word: 'answer' }, b: { word: 'ответ / отвечать' } },
  { _id: 339, a: { word: 'sit' }, b: { word: 'сидеть' } },
  { _id: 340, a: { word: 'figure' }, b: { word: 'фигура / понимать' } },
  { _id: 341, a: { word: 'letter' }, b: { word: 'письмо / буква' } },
  { _id: 342, a: { word: 'decide' }, b: { word: 'решать' } },
  { _id: 343, a: { word: 'language' }, b: { word: 'язык' } },
  { _id: 344, a: { word: 'subject' }, b: { word: 'тема / предмет' } },
  { _id: 345, a: { word: 'class' }, b: { word: 'класс / занятие' } },
  { _id: 346, a: { word: 'development' }, b: { word: 'развитие' } },
  { _id: 347, a: { word: 'town' }, b: { word: 'городок' } },
  { _id: 348, a: { word: 'half' }, b: { word: 'половина' } },
  { _id: 349, a: { word: 'minute' }, b: { word: 'минута' } },
  { _id: 350, a: { word: 'food' }, b: { word: 'еда' } },
  { _id: 351, a: { word: 'break' }, b: { word: 'ломать / перерыв' } },
  { _id: 352, a: { word: 'clear' }, b: { word: 'ясный / очищать' } },
  { _id: 353, a: { word: 'future' }, b: { word: 'будущее' } },
  { _id: 354, a: { word: 'either' }, b: { word: 'либо / тоже (в отриц.)' } },
  { _id: 355, a: { word: 'ago' }, b: { word: 'назад' } },
  { _id: 356, a: { word: 'per' }, b: { word: 'на / за' } },
  { _id: 357, a: { word: 'remain' }, b: { word: 'оставаться' } },
  { _id: 358, a: { word: 'top' }, b: { word: 'верх / лучший' } },
  { _id: 359, a: { word: 'among' }, b: { word: 'среди' } },
  { _id: 360, a: { word: 'win' }, b: { word: 'побеждать / выигрывать' } },
  { _id: 361, a: { word: 'color' }, b: { word: 'цвет' } },
  { _id: 362, a: { word: 'involve' }, b: { word: 'вовлекать / включать' } },
  { _id: 363, a: { word: 'reach' }, b: { word: 'достигать' } },
  { _id: 364, a: { word: 'social' }, b: { word: 'социальный' } },
  { _id: 365, a: { word: 'period' }, b: { word: 'период' } },
  { _id: 366, a: { word: 'across' }, b: { word: 'через / поперёк' } },
  { _id: 367, a: { word: 'note' }, b: { word: 'заметка / отмечать' } },
  { _id: 368, a: { word: 'history' }, b: { word: 'история' } },
  { _id: 369, a: { word: 'create' }, b: { word: 'создавать' } },
  { _id: 370, a: { word: 'drive' }, b: { word: 'вести (машину) / драйв' } },
  { _id: 371, a: { word: 'along' }, b: { word: 'вдоль / вместе' } },
  { _id: 372, a: { word: 'type' }, b: { word: 'тип / печатать' } },
  { _id: 373, a: { word: 'sound' }, b: { word: 'звук / звучать' } },
  { _id: 374, a: { word: 'eye' }, b: { word: 'глаз' } },
  { _id: 375, a: { word: 'music' }, b: { word: 'музыка' } },
  { _id: 376, a: { word: 'game' }, b: { word: 'игра' } },
  { _id: 377, a: { word: 'political' }, b: { word: 'политический' } },
  { _id: 378, a: { word: 'free' }, b: { word: 'свободный / бесплатный' } },
  { _id: 379, a: { word: 'receive' }, b: { word: 'получать' } },
  { _id: 380, a: { word: 'moment' }, b: { word: 'момент' } },
  { _id: 381, a: { word: 'sale' }, b: { word: 'продажа / распродажа' } },
  { _id: 382, a: { word: 'policy' }, b: { word: 'политика / правило' } },
  { _id: 383, a: { word: 'further' }, b: { word: 'дальнейший / далее' } },
  { _id: 384, a: { word: 'body' }, b: { word: 'тело / орган' } },
  { _id: 385, a: { word: 'require' }, b: { word: 'требовать' } },
  { _id: 386, a: { word: 'wait' }, b: { word: 'ждать' } },
  { _id: 387, a: { word: 'general' }, b: { word: 'общий / генерал' } },
  { _id: 388, a: { word: 'appear' }, b: { word: 'появляться' } },
  { _id: 389, a: { word: 'toward' }, b: { word: 'к / по направлению к' } },
  { _id: 390, a: { word: 'team' }, b: { word: 'команда' } },
  { _id: 391, a: { word: 'easy' }, b: { word: 'лёгкий / просто' } },
  { _id: 392, a: { word: 'individual' }, b: { word: 'индивидуальный / человек' } },
  { _id: 393, a: { word: 'full' }, b: { word: 'полный' } },
  { _id: 394, a: { word: 'black' }, b: { word: 'чёрный' } },
  { _id: 395, a: { word: 'sense' }, b: { word: 'смысл / чувство' } },
  { _id: 396, a: { word: 'perhaps' }, b: { word: 'возможно' } },
  { _id: 397, a: { word: 'add' }, b: { word: 'добавлять' } },
  { _id: 398, a: { word: 'rule' }, b: { word: 'правило / управлять' } },
  { _id: 399, a: { word: 'pass' }, b: { word: 'проходить / передавать' } },
  { _id: 400, a: { word: 'produce' }, b: { word: 'производить' } },
  { _id: 401, a: { word: 'sell' }, b: { word: 'продавать' } },
  { _id: 402, a: { word: 'short' }, b: { word: 'короткий / краткий' } },
  { _id: 403, a: { word: 'agree' }, b: { word: 'соглашаться' } },
  { _id: 404, a: { word: 'law' }, b: { word: 'закон' } },
  { _id: 405, a: { word: 'everything' }, b: { word: 'всё' } },
  { _id: 406, a: { word: 'research' }, b: { word: 'исследование / исследовать' } },
  { _id: 407, a: { word: 'cover' }, b: { word: 'покрывать / обложка' } },
  { _id: 408, a: { word: 'paper' }, b: { word: 'бумага / статья' } },
  { _id: 409, a: { word: 'position' }, b: { word: 'позиция / должность' } },
  { _id: 410, a: { word: 'near' }, b: { word: 'рядом / близко' } },
  { _id: 411, a: { word: 'human' }, b: { word: 'человек / человеческий' } },
  { _id: 412, a: { word: 'computer' }, b: { word: 'компьютер' } },
  { _id: 413, a: { word: 'situation' }, b: { word: 'ситуация' } },
  { _id: 414, a: { word: 'staff' }, b: { word: 'персонал / сотрудники' } },
  { _id: 415, a: { word: 'activity' }, b: { word: 'деятельность / активность' } },
  { _id: 416, a: { word: 'film' }, b: { word: 'фильм / плёнка' } },
  { _id: 417, a: { word: 'morning' }, b: { word: 'утро' } },
  { _id: 418, a: { word: 'war' }, b: { word: 'война' } },
  { _id: 419, a: { word: 'account' }, b: { word: 'счёт / аккаунт' } },
  { _id: 420, a: { word: 'shop' }, b: { word: 'магазин / покупать' } },
  { _id: 421, a: { word: 'major' }, b: { word: 'основной / главный' } },
  { _id: 422, a: { word: 'someone' }, b: { word: 'кто-то' } },
  { _id: 423, a: { word: 'above' }, b: { word: 'выше / над' } },
  { _id: 424, a: { word: 'design' }, b: { word: 'дизайн / проектировать' } },
  { _id: 425, a: { word: 'event' }, b: { word: 'событие' } },
  { _id: 426, a: { word: 'special' }, b: { word: 'особый / специальный' } },
  { _id: 427, a: { word: 'sometimes' }, b: { word: 'иногда' } },
  { _id: 428, a: { word: 'condition' }, b: { word: 'условие / состояние' } },
  { _id: 429, a: { word: 'carry' }, b: { word: 'нести / переносить' } },
  { _id: 430, a: { word: 'choose' }, b: { word: 'выбирать' } },
  { _id: 431, a: { word: 'father' }, b: { word: 'отец' } },
  { _id: 432, a: { word: 'decision' }, b: { word: 'решение' } },
  { _id: 433, a: { word: 'table' }, b: { word: 'стол / таблица' } },
  { _id: 434, a: { word: 'certain' }, b: { word: 'определённый / уверенный' } },
  { _id: 435, a: { word: 'forward' }, b: { word: 'вперёд / пересылать' } },
  { _id: 436, a: { word: 'main' }, b: { word: 'главный' } },
  { _id: 437, a: { word: 'die' }, b: { word: 'умирать' } },
  { _id: 438, a: { word: 'bear' }, b: { word: 'нести / выносить' } },
  { _id: 439, a: { word: 'cut' }, b: { word: 'резать / сокращать' } },
  { _id: 440, a: { word: 'describe' }, b: { word: 'описывать' } },
  { _id: 441, a: { word: 'himself' }, b: { word: 'сам / себя' } },
  { _id: 442, a: { word: 'available' }, b: { word: 'доступный / имеющийся' } },
  { _id: 443, a: { word: 'especially' }, b: { word: 'особенно' } },
  { _id: 444, a: { word: 'strong' }, b: { word: 'сильный' } },
  { _id: 445, a: { word: 'rise' }, b: { word: 'подниматься / рост' } },
  { _id: 446, a: { word: 'girl' }, b: { word: 'девушка / девочка' } },
  { _id: 447, a: { word: 'maybe' }, b: { word: 'может быть' } },
  { _id: 448, a: { word: 'community' }, b: { word: 'сообщество' } },
  { _id: 449, a: { word: 'else' }, b: { word: 'ещё / другой' } },
  { _id: 450, a: { word: 'particular' }, b: { word: 'конкретный / особый' } },
  { _id: 451, a: { word: 'role' }, b: { word: 'роль' } },
  { _id: 452, a: { word: 'join' }, b: { word: 'присоединяться' } },
  { _id: 453, a: { word: 'difficult' }, b: { word: 'сложный / трудный' } },
  { _id: 454, a: { word: 'please' }, b: { word: 'пожалуйста / радовать' } },
  { _id: 455, a: { word: 'detail' }, b: { word: 'деталь / подробность' } },
  { _id: 456, a: { word: 'difference' }, b: { word: 'разница' } },
  { _id: 457, a: { word: 'action' }, b: { word: 'действие' } },
  { _id: 458, a: { word: 'health' }, b: { word: 'здоровье' } },
  { _id: 459, a: { word: 'eat' }, b: { word: 'есть / кушать' } },
  { _id: 460, a: { word: 'step' }, b: { word: 'шаг' } },
  { _id: 461, a: { word: 'TRUE' }, b: { word: 'истина / верно' } },
  { _id: 462, a: { word: 'phone' }, b: { word: 'телефон' } },
  { _id: 463, a: { word: 'themselves' }, b: { word: 'сами / себя' } },
  { _id: 464, a: { word: 'draw' }, b: { word: 'рисовать / тянуть' } },
  { _id: 465, a: { word: 'white' }, b: { word: 'белый' } },
  { _id: 466, a: { word: 'date' }, b: { word: 'дата / свидание' } },
  { _id: 467, a: { word: 'practice' }, b: { word: 'практика / практиковать' } },
  { _id: 468, a: { word: 'model' }, b: { word: 'модель' } },
  { _id: 469, a: { word: 'raise' }, b: { word: 'поднимать / повышать' } },
  { _id: 470, a: { word: 'customer' }, b: { word: 'клиент / покупатель' } },
  { _id: 471, a: { word: 'front' }, b: { word: 'перед / фасад' } },
  { _id: 472, a: { word: 'explain' }, b: { word: 'объяснять' } },
  { _id: 473, a: { word: 'door' }, b: { word: 'дверь' } },
  { _id: 474, a: { word: 'outside' }, b: { word: 'снаружи / внешний' } },
  { _id: 475, a: { word: 'behind' }, b: { word: 'позади / за' } },
  { _id: 476, a: { word: 'economic' }, b: { word: 'экономический' } },
  { _id: 477, a: { word: 'site' }, b: { word: 'сайт / место' } },
  { _id: 478, a: { word: 'approach' }, b: { word: 'подход / приближаться' } },
  { _id: 479, a: { word: 'teacher' }, b: { word: 'учитель' } },
  { _id: 480, a: { word: 'land' }, b: { word: 'земля / территория' } },
  { _id: 481, a: { word: 'charge' }, b: { word: 'плата / заряжать' } },
  { _id: 482, a: { word: 'finally' }, b: { word: 'наконец' } },
  { _id: 483, a: { word: 'sign' }, b: { word: 'знак / подписывать' } },
];

export const cardsHundreds = [
  {
    _id: 1,
    items: Array.from({ length: 83 }, (_, i) => i + 1),
  },
  {
    _id: 2,
    items: Array.from({ length: 100 }, (_, i) => i + 84),
  },
  {
    _id: 3,
    items: Array.from({ length: 100 }, (_, i) => i + 184),
  },
  {
    _id: 4,
    items: Array.from({ length: 100 }, (_, i) => i + 284),
  },
  {
    _id: 5,
    items: Array.from({ length: 100 }, (_, i) => i + 384),
  }
];

// export const token = '4d2fc48f-d0c7-4bea-a8e0-385b9ccc8f15';
// export const baseUrl = 'https://mesto.nomoreparties.co/v1/cohort-75';

// export const profileElementsSelectors = {
//   userNameElementSelector: '.profile__name',
//   userRoleElementSelector: '.profile__role',
//   userAvatarElementSelector: '.profile__avatar-image',
// };

// export const profilePopupSelector = '.js-profile-popup';
// export const placePopupSelector = '.js-place-popup';
// export const imagePopupSelector = '.js-image-popup';
// export const deletePopupSelector = '.js-delete-popup';
// export const avatarPopupSelector = '.js-avatar-popup';
// export const elementsContainerSelector = '.elements';