export const cardsArr = [
  { _id: 1, a: { word: 'have' }, b: { word: 'иметь' } },
  { _id: 2, a: { word: 'you' }, b: { word: 'ты / вы' } },
  { _id: 3, a: { word: 'he' }, b: { word: 'он' } },
  { _id: 4, a: { word: 'they' }, b: { word: 'они' } },
  { _id: 5, a: { word: 'that' }, b: { word: 'что / тот' } },
  { _id: 6, a: { word: 'we' }, b: { word: 'мы' } },
  { _id: 7, a: { word: 'i' }, b: { word: 'я' } },
  { _id: 8, a: { word: 'she' }, b: { word: 'она' } },
  { _id: 9, a: { word: 'but' }, b: { word: 'но' } },
  { _id: 10, a: { word: 'from' }, b: { word: 'из / от' } },
  { _id: 11, a: { word: 'will' }, b: { word: 'будет / воля' } },
  { _id: 12, a: { word: 'or' }, b: { word: 'или' } },
  { _id: 13, a: { word: 'say' }, b: { word: 'сказать' } },
  { _id: 14, a: { word: 'go' }, b: { word: 'идти' } },
  { _id: 15, a: { word: 'so' }, b: { word: 'так / поэтому' } },
  { _id: 16, a: { word: 'all' }, b: { word: 'все' } },
  { _id: 17, a: { word: 'if' }, b: { word: 'если' } },
  { _id: 18, a: { word: 'one' }, b: { word: 'один' } },
  { _id: 19, a: { word: 'would' }, b: { word: 'бы' } },
  { _id: 20, a: { word: 'about' }, b: { word: 'о / около' } },
  { _id: 21, a: { word: 'can' }, b: { word: 'мочь' } },
  { _id: 22, a: { word: 'which' }, b: { word: 'который' } },
  { _id: 23, a: { word: 'there' }, b: { word: 'там' } },
  { _id: 24, a: { word: 'know' }, b: { word: 'знать' } },
  { _id: 25, a: { word: 'more' }, b: { word: 'больше' } },
  { _id: 26, a: { word: 'get' }, b: { word: 'получать' } },
  { _id: 27, a: { word: 'who' }, b: { word: 'кто' } },
  { _id: 28, a: { word: 'like' }, b: { word: 'нравиться / как' } },
  { _id: 29, a: { word: 'when' }, b: { word: 'когда' } },
  { _id: 30, a: { word: 'think' }, b: { word: 'думать' } },
  { _id: 31, a: { word: 'make' }, b: { word: 'делать' } },
  { _id: 32, a: { word: 'time' }, b: { word: 'время' } },
  { _id: 33, a: { word: 'see' }, b: { word: 'видеть' } },
  { _id: 34, a: { word: 'what' }, b: { word: 'что' } },
  { _id: 35, a: { word: 'up' }, b: { word: 'вверх' } },
  { _id: 36, a: { word: 'some' }, b: { word: 'некоторые' } },
  { _id: 37, a: { word: 'other' }, b: { word: 'другой' } },
  { _id: 38, a: { word: 'out' }, b: { word: 'вне / наружу' } },
  { _id: 39, a: { word: 'good' }, b: { word: 'хороший' } },
  { _id: 40, a: { word: 'people' }, b: { word: 'люди' } },
  { _id: 41, a: { word: 'year' }, b: { word: 'год' } },
  { _id: 42, a: { word: 'take' }, b: { word: 'брать' } },
  { _id: 43, a: { word: 'no' }, b: { word: 'нет' } },
  { _id: 44, a: { word: 'well' }, b: { word: 'хорошо' } },
  { _id: 45, a: { word: 'because' }, b: { word: 'потому что' } },
  { _id: 46, a: { word: 'very' }, b: { word: 'очень' } },
  { _id: 47, a: { word: 'just' }, b: { word: 'просто / только' } },
  { _id: 48, a: { word: 'come' }, b: { word: 'приходить' } },
  { _id: 49, a: { word: 'could' }, b: { word: 'мог бы' } },
  { _id: 50, a: { word: 'work' }, b: { word: 'работа / работать' } },
  { _id: 51, a: { word: 'use' }, b: { word: 'использовать' } },
  { _id: 52, a: { word: 'than' }, b: { word: 'чем' } },
  { _id: 53, a: { word: 'now' }, b: { word: 'сейчас' } },
  { _id: 54, a: { word: 'then' }, b: { word: 'тогда' } },
  { _id: 55, a: { word: 'also' }, b: { word: 'также' } },
  { _id: 56, a: { word: 'into' }, b: { word: 'внутрь' } },
  { _id: 57, a: { word: 'only' }, b: { word: 'только' } },
  { _id: 58, a: { word: 'look' }, b: { word: 'смотреть' } },
  { _id: 59, a: { word: 'want' }, b: { word: 'хотеть' } },
  { _id: 60, a: { word: 'give' }, b: { word: 'давать' } },
  { _id: 61, a: { word: 'first' }, b: { word: 'первый' } },
  { _id: 62, a: { word: 'new' }, b: { word: 'новый' } },
  { _id: 63, a: { word: 'way' }, b: { word: 'путь / способ' } },
  { _id: 64, a: { word: 'find' }, b: { word: 'находить' } },
  { _id: 65, a: { word: 'over' }, b: { word: 'над / через' } },
  { _id: 66, a: { word: 'any' }, b: { word: 'любой' } },
  { _id: 67, a: { word: 'after' }, b: { word: 'после' } },
  { _id: 68, a: { word: 'day' }, b: { word: 'день' } },
  { _id: 69, a: { word: 'where' }, b: { word: 'где' } },
  { _id: 70, a: { word: 'thing' }, b: { word: 'вещь' } },
  { _id: 71, a: { word: 'most' }, b: { word: 'большинство' } },
  { _id: 72, a: { word: 'should' }, b: { word: 'должен' } },
  { _id: 73, a: { word: 'need' }, b: { word: 'нуждаться' } },
  { _id: 74, a: { word: 'much' }, b: { word: 'много' } },
  { _id: 75, a: { word: 'right' }, b: { word: 'правильный / право' } },
  { _id: 76, a: { word: 'how' }, b: { word: 'как' } },
  { _id: 77, a: { word: 'back' }, b: { word: 'назад' } },
  { _id: 78, a: { word: 'mean' }, b: { word: 'значить' } },
  { _id: 79, a: { word: 'even' }, b: { word: 'даже' } },
  { _id: 80, a: { word: 'may' }, b: { word: 'мочь / май' } },
  { _id: 81, a: { word: 'here' }, b: { word: 'здесь' } },
  { _id: 82, a: { word: 'many' }, b: { word: 'многие' } },
  { _id: 83, a: { word: 'such' }, b: { word: 'такой' } },
  { _id: 84, a: { word: 'last' }, b: { word: 'последний' } },
  { _id: 85, a: { word: 'child' }, b: { word: 'ребенок' } },
  { _id: 86, a: { word: 'tell' }, b: { word: 'рассказывать' } },
  { _id: 87, a: { word: 'really' }, b: { word: 'действительно' } },
  { _id: 88, a: { word: 'call' }, b: { word: 'звонить' } },
  { _id: 89, a: { word: 'before' }, b: { word: 'до' } },
  { _id: 90, a: { word: 'company' }, b: { word: 'компания' } },
  { _id: 91, a: { word: 'through' }, b: { word: 'через' } },
  { _id: 92, a: { word: 'down' }, b: { word: 'вниз' } },
  { _id: 93, a: { word: 'show' }, b: { word: 'показывать' } },
  { _id: 94, a: { word: 'life' }, b: { word: 'жизнь' } },
  { _id: 95, a: { word: 'man' }, b: { word: 'мужчина' } },
  { _id: 96, a: { word: 'change' }, b: { word: 'изменять' } },
  { _id: 97, a: { word: 'place' }, b: { word: 'место' } },
  { _id: 98, a: { word: 'long' }, b: { word: 'долгий' } },
  { _id: 99, a: { word: 'between' }, b: { word: 'между' } },
  { _id: 100, a: { word: 'feel' }, b: { word: 'чувствовать' } },
  { _id: 101, a: { word: 'too' }, b: { word: 'слишком' } },
  { _id: 102, a: { word: 'still' }, b: { word: 'все еще' } },
  { _id: 103, a: { word: 'problem' }, b: { word: 'проблема' } },
  { _id: 104, a: { word: 'write' }, b: { word: 'писать' } },
  { _id: 105, a: { word: 'same' }, b: { word: 'тот же' } },
  { _id: 106, a: { word: 'lot' }, b: { word: 'много' } },
  { _id: 107, a: { word: 'great' }, b: { word: 'отличный' } },
  { _id: 108, a: { word: 'try' }, b: { word: 'пытаться' } },
  { _id: 109, a: { word: 'leave' }, b: { word: 'оставлять' } },
  { _id: 110, a: { word: 'number' }, b: { word: 'число' } },
  { _id: 111, a: { word: 'both' }, b: { word: 'оба' } },
  { _id: 112, a: { word: 'own' }, b: { word: 'собственный' } },
  { _id: 113, a: { word: 'part' }, b: { word: 'часть' } },
  { _id: 114, a: { word: 'point' }, b: { word: 'точка' } },
  { _id: 115, a: { word: 'little' }, b: { word: 'маленький' } },
  { _id: 116, a: { word: 'help' }, b: { word: 'помогать' } },
  { _id: 117, a: { word: 'ask' }, b: { word: 'спрашивать' } },
  { _id: 118, a: { word: 'meet' }, b: { word: 'встречать' } },
  { _id: 119, a: { word: 'start' }, b: { word: 'начинать' } },
  { _id: 120, a: { word: 'talk' }, b: { word: 'говорить' } },
  { _id: 121, a: { word: 'something' }, b: { word: 'что-то' } },
  { _id: 122, a: { word: 'put' }, b: { word: 'класть' } },
  { _id: 123, a: { word: 'another' }, b: { word: 'другой' } },
  { _id: 124, a: { word: 'become' }, b: { word: 'становиться' } },
  { _id: 125, a: { word: 'interest' }, b: { word: 'интерес' } },
  { _id: 126, a: { word: 'country' }, b: { word: 'страна' } },
  { _id: 127, a: { word: 'old' }, b: { word: 'старый' } },
  { _id: 128, a: { word: 'each' }, b: { word: 'каждый' } },
  { _id: 129, a: { word: 'school' }, b: { word: 'школа' } },
  { _id: 130, a: { word: 'late' }, b: { word: 'поздний' } },
  { _id: 131, a: { word: 'high' }, b: { word: 'высокий' } },
  { _id: 132, a: { word: 'different' }, b: { word: 'разный' } },
  { _id: 133, a: { word: 'off' }, b: { word: 'выключен' } },
  { _id: 134, a: { word: 'next' }, b: { word: 'следующий' } },
  { _id: 135, a: { word: 'end' }, b: { word: 'конец' } },
  { _id: 136, a: { word: 'live' }, b: { word: 'жить' } },
  { _id: 137, a: { word: 'why' }, b: { word: 'почему' } },
  { _id: 138, a: { word: 'while' }, b: { word: 'пока' } },
  { _id: 139, a: { word: 'world' }, b: { word: 'мир' } },
  { _id: 140, a: { word: 'week' }, b: { word: 'неделя' } },
  { _id: 141, a: { word: 'play' }, b: { word: 'играть' } },
  { _id: 142, a: { word: 'might' }, b: { word: 'мочь' } },
  { _id: 143, a: { word: 'must' }, b: { word: 'должен' } },
  { _id: 144, a: { word: 'home' }, b: { word: 'дом' } },
  { _id: 145, a: { word: 'never' }, b: { word: 'никогда' } },
  { _id: 146, a: { word: 'include' }, b: { word: 'включать' } },
  { _id: 147, a: { word: 'course' }, b: { word: 'курс' } },
  { _id: 148, a: { word: 'house' }, b: { word: 'дом' } },
  { _id: 149, a: { word: 'report' }, b: { word: 'отчет' } },
  { _id: 150, a: { word: 'group' }, b: { word: 'группа' } },
  { _id: 151, a: { word: 'case' }, b: { word: 'случай' } },
  { _id: 152, a: { word: 'woman' }, b: { word: 'женщина' } },
  { _id: 153, a: { word: 'around' }, b: { word: 'вокруг' } },
  { _id: 154, a: { word: 'book' }, b: { word: 'книга' } },
  { _id: 155, a: { word: 'family' }, b: { word: 'семья' } },
  { _id: 156, a: { word: 'seem' }, b: { word: 'казаться' } },
  { _id: 157, a: { word: 'let' }, b: { word: 'позволять' } },
  { _id: 158, a: { word: 'again' }, b: { word: 'снова' } },
  { _id: 159, a: { word: 'kind' }, b: { word: 'вид / добрый' } },
  { _id: 160, a: { word: 'keep' }, b: { word: 'держать' } },
  { _id: 161, a: { word: 'hear' }, b: { word: 'слышать' } },
  { _id: 162, a: { word: 'system' }, b: { word: 'система' } },
  { _id: 163, a: { word: 'every' }, b: { word: 'каждый' } },
  { _id: 164, a: { word: 'question' }, b: { word: 'вопрос' } },
  { _id: 165, a: { word: 'during' }, b: { word: 'во время' } },
  { _id: 166, a: { word: 'always' }, b: { word: 'всегда' } },
  { _id: 167, a: { word: 'big' }, b: { word: 'большой' } },
  { _id: 168, a: { word: 'set' }, b: { word: 'набор / устанавливать' } },
  { _id: 169, a: { word: 'small' }, b: { word: 'маленький' } },
  { _id: 170, a: { word: 'study' }, b: { word: 'учиться' } },
  { _id: 171, a: { word: 'follow' }, b: { word: 'следовать' } },
  { _id: 172, a: { word: 'begin' }, b: { word: 'начинать' } },
  { _id: 173, a: { word: 'important' }, b: { word: 'важный' } },
  { _id: 174, a: { word: 'since' }, b: { word: 'с тех пор как' } },
  { _id: 175, a: { word: 'run' }, b: { word: 'бежать' } },
  { _id: 176, a: { word: 'under' }, b: { word: 'под' } },
  { _id: 177, a: { word: 'turn' }, b: { word: 'поворачивать' } },
  { _id: 178, a: { word: 'few' }, b: { word: 'несколько' } },
  { _id: 179, a: { word: 'bring' }, b: { word: 'приносить' } },
  { _id: 180, a: { word: 'early' }, b: { word: 'ранний' } },
  { _id: 181, a: { word: 'hand' }, b: { word: 'рука' } },
  { _id: 182, a: { word: 'state' }, b: { word: 'состояние / штат' } },
  { _id: 183, a: { word: 'move' }, b: { word: 'двигаться' } },
];

export const cardsHundreds = [
  {
    _id: 1,
    items: Array.from({ length: 83 }, (_, i) => i + 1),
  },
  {
    _id: 2,
    items: Array.from({ length: 100 }, (_, i) => i + 84),
  },
  {
    _id: 3,
    items: Array.from({ length: 100 }, (_, i) => i + 184),
  }
];

// export const token = '4d2fc48f-d0c7-4bea-a8e0-385b9ccc8f15';
// export const baseUrl = 'https://mesto.nomoreparties.co/v1/cohort-75';

// export const profileElementsSelectors = {
//   userNameElementSelector: '.profile__name',
//   userRoleElementSelector: '.profile__role',
//   userAvatarElementSelector: '.profile__avatar-image',
// };

// export const profilePopupSelector = '.js-profile-popup';
// export const placePopupSelector = '.js-place-popup';
// export const imagePopupSelector = '.js-image-popup';
// export const deletePopupSelector = '.js-delete-popup';
// export const avatarPopupSelector = '.js-avatar-popup';
// export const elementsContainerSelector = '.elements';